import { Affair } from "../main/db/entities/Affair";
import sectorialJointAgreementSlice from "./redux/sectorialJointAgreement/sectorialJointAgreementSlice";

export const labels = {
  home: 'الرئيسية',
  sectorialJointAgreement: 'الاتفقيات المشتركة',
  sectorialJointAgreementName: 'اسم الاتفاقية القطاعية المشتركة',
  descriptionSectorialJointAgreement: "بيانات على الاتفاقية القطاعية المشتركة",
  addSectorialJointAgreement: 'اضافة اتفاقية',
  category: 'الصنف',
  removeCategory: 'حذف الصنف',
  degree: 'مرتبة',
  removeDegree: 'حذف المرتبة',
  addDegree: 'اضافة مرتبة',
  addCategory: 'اضافة الصنف',
  ageOfWork: 'الاقدمية الفعلية',
  cancel: 'الغاء',
  save: 'حفظ',
  saved: 'تم الحفظ',
  update: 'تحديث',
  updated: 'تم التحديث',
  deleted: 'تم الحذف',
  delete: 'حذف',
  create: 'اضافة',
  created: 'تم الاضافة',
  successfully: 'تمت العملية بنجاح',
  failed: 'فشلت العملية',
  idle: 'معلقة',
  loading: 'تحميل',
  error: 'خطأ',
  success: 'نجاح',
  action: 'العمليات',
  sectorialJointAgreementList: 'قائمة الاتفاقيات القطاعية المشتركة',
  sectorialJointAgreementApplicationPeriods: "مدة تطبيق الاتفاقيات القطاعية المشتركة",
  affairs: "القضايا",
  affair: "القضية",
  salaryTableList: "قائمة جداول الاجور",
  addSalaryTable: "اضافة جدول الاجور",
  salaryTableNumber: "رقم الجدول الاجور",
  salaryType: "نوع جدول الاجور",
  selectSalaryType: "حدد نوع جدول الاجور",
  salaryTypeByHour: "جدول الاجور بالساعة",
  salaryTypeByMonth: "جدول الاجور بالشهر",
  concernedEmployee: "الموضفون المعنيين",
  selectAgreement: "حدد الاتفاقية",
  salaryTableForm: "نموذج جدول الاجور",
  beginningDateOfApplication: "تاريخ بدئة التطبيق",
  endDateOfApplication: "تاريخ نهاية التطبيق",
};