export const labels = {
    home: 'الرئيسية',
    conventionCollective: 'الاتفقيات المشتركة',
    sectorialJointAgreementName:'اسم الاتفاقية القطاعية المشتركة',
    descriptionSectorialJointAgreement: "بيانات على الاتفاقية القطاعية المشتركة",
    category: 'فئة',
    degree:'مرتبة',
    cancel:'الغاء',
    save:'حفظ',
    update:'تحديث',
    delete:'حذف',
    create:'اضافة',
    loading:'تحميل',
    error:'خطأ',
    success:'نجاح',
    action:'العمليات',
    sectorialJointAgreementList:'قائمة الاتفاقيات القطاعية المشتركة',
    sectorialJointAgreementApplicationPeriods:"مدة التطبيق في الاتفاقيات القطاعية المشتركة",

  };