import { Affair } from "../main/db/entities/Affair";
import sectorialJointAgreementSlice from "./redux/sectorialJointAgreement/sectorialJointAgreementSlice";

export const labels = {
  home: 'الرئيسية',
  sectorialJointAgreement: 'الاتفقيات المشتركة',
  sectorialJointAgreementName: 'اسم الاتفاقية القطاعية المشتركة',
  descriptionSectorialJointAgreement: "بيانات على الاتفاقية القطاعية المشتركة",
  addSectorialJointAgreement: 'اضافة اتفاقية',
  category: 'فئة',
  degree: 'مرتبة',
  cancel: 'الغاء',
  save: 'حفظ',
  update: 'تحديث',
  delete: 'حذف',
  create: 'اضافة',
  loading: 'تحميل',
  error: 'خطأ',
  success: 'نجاح',
  action: 'العمليات',
  sectorialJointAgreementList: 'قائمة الاتفاقيات القطاعية المشتركة',
  sectorialJointAgreementApplicationPeriods: "مدة تطبيق الاتفاقيات القطاعية المشتركة",
  affairs: "القضايا",
  affair: "القضية",
  salaryTableList: "قائمة جداول الاجور",
  addSalaryTable: "اضافة جدول الاجور",
  salaryTableNumber: "رقم الجدول الاجور",
  salaryType: "نوع جدول الاجور",
  selectSalaryType: "حدد نوع جدول الاجور",
  salaryTypeByHour: "جدول الاجور بالساعة",
  salaryTypeByMonth: "جدول الاجور بالشهر",
  concernedEmployee:"الموضفون المعنيين",
  selectAgreement: "حدد الاتفاقية",
  salaryTableForm: "نموذج جدول الاجور",
  beginningDateOfApplication: "تاريخ بدئة التطبيق",
  endDateOfApplication: "تاريخ نهاية التطبيق",
};